number: 'à¥¦à¥§à¥¨à¥©à¥ªà¥«à¥¬à¥­à¥®à¥¯'
symbol: "ğ‘‚»ğ‘‚½ğ‘‚¼ğ‘‚¾ğ‘‚¿ğ‘ƒ€ğ‘ƒ"
lang_char: 'ğ‘‚ƒğ‘‚„ğ‘‚…ğ‘‚†ğ‘‚‡ğ‘‚ˆğ‘‚‰ğ‘‚Šğ‘‚‹ğ‘‚Œğ‘‚ğ‘‚ğ‘‚ğ‘‚ğ‘‚‘ğ‘‚’ğ‘‚“ğ‘‚”ğ‘‚•ğ‘‚–ğ‘‚—ğ‘‚˜ğ‘‚™ğ‘‚šğ‘‚›ğ‘‚œğ‘‚ğ‘‚ğ‘‚Ÿğ‘‚ ğ‘‚¡ğ‘‚¢ğ‘‚£ğ‘‚¤ğ‘‚¥ğ‘‚¦ğ‘‚§ğ‘‚¨ğ‘‚©ğ‘‚ªğ‘‚«ğ‘‚¬ğ‘‚­ğ‘‚®ğ‘‚¯'
experiment_name: 'kthi_filtered'
train_data: 'all_data'
valid_data: 'all_data/kthi_val'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 300000
valInterval: 20000
saved_model: '' #'saved_models/kthi_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'kthi_train_filtered' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False